[package]
name = "chat-context-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "=0.5.0-rc.3", features = ["secrets", "tls", "json"] }

[lib]
name = "ccp"
path = "src/lib.rs"

[[bin]]
name = "chat-context-provider-server"
path = "src/main.rs"
